### ISSUE TITLE
What do you think about using Pickle?

### ISSUE THREAD

**Issue by creationyun** [saidsef/ml-classifier#17]
Hello. I am a student of the Department of Computer Science at Korea University. I have researched about security and system since 2017.

First of all, thank you for creating a machine learning news classification program, and I am very interested in this repository. However, I want to talk about the pickle module usage. When I was researching about the pickle vulnerability, then I found this repository on April, 2020. It uses randomforestclassifier.pickle file and loads on the server.
The pickle module can basically do anything (called arbitrary code execution, ACE) and is vulnerable. If this project upgrades version or complicates, you may consider not to use pickle.

In the classifier-ml.py file, there are no hash integrity verification or the RSA digital signature for preventing pickle vulnerability. Fortunately, news.json file is a JSON file which cannot do ACE, so I think you did a good job with this part.

Please consider the patch of the pickle module. Thank you.

**Comment by saidsef** [comment]
@creationyun hi and thanks for raising the issue.

This has dropped of my raider due to work and family commitment, was cleaning/clearing the repo and juts saw this was still outstanding.

You are absolutely correct,  hash integrity verification or the RSA digital signature to preventing pickle vulnerability will improve security posture.  As a first step I have added hash sum256sum along with the pickles during CI release workflow - so users can independently verify files, the next step in `classifier-ml.py` I will add a check before loading the model.
